spring:
  application:
    name: dan-fund-messenger-service
  kafka:
    consumer:
      group-id: ${spring.application.name}
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: KafkaStreetOrderDTO.v1:com.danservice.fundmessenger.adapter.inbound.kafka.streetorder.v1.dto.KafkaStreetOrderDTO
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      retries: 3
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: KafkaStreetOrderAckDTO.v1:com.danservice.fundmessenger.adapter.outbound.kafka.streetorderack.v1.dto.KafkaStreetOrderAckDTO

dan:
  topic:
    street-order: dan-street-orders
    street-order-ack: dan-street-order-acks
    street-order-execution: dan-street-order-executions
    int-fund-messenger-execution: int-fund-messenger-execution
